w3-vip = https,https://w3-vip.com/api/v1/client/subscribe?token=2b127f7b0da47d374547967859f70f23,update-interval=3600,format=auto,emoji=true,skip-cert-verify=true,filter=(HK|Hong|香港|JP|Japan|日本|SG|Sing|新加坡|TW|Taiwan|台灣),exclude-filter=(IEPL|IPLC)
HK-Mix = select,dmit-HKD-51688,dmit-HKD-51689,wee-HKW-51688,wee-HKW-51689,provider=w3-vip,regex-filter=(HK|Hong|香港),DIRECT
JP-Mix = select,fxt-JP-55555,provider=w3-vip,regex-filter=(JP|Japan|日本),DIRECT
SG-Mix = select,aws-SG-55555,provider=w3-vip,regex-filter=(SG|Sing|新加坡),DIRECT
TW-Mix = select,provider=w3-vip,regex-filter=(TW|Taiwan|台灣),DIRECT